###############################################################################
## This configuration is intended for development.
##
##  Create a toml table for each listener as required, this example is defining
## 2 listeners called "public" and "private". At this time there is no special
## configuration other than the network interface and port. In the roadmap the
## listeners will have different configurable behaviours.
##
###############################################################################

[listener.public]
# This should be the address that is accesible from the internet/public network.
ip = "0.0.0.0"
port = 8080

[listener.private]
# This should be the address that is accesible only from the internal network.
ip = "0.0.0.0"
port = 8081

