
[listener.public]
# This should be the address that is accesible from the internet/public network.
ip = "0.0.0.0"
port = 8080

[listener.private]
# This should be the address that is accesible only from the internal network.
ip = "0.0.0.0"
port = 8081

